controller_manager:
  ros__parameters:
    update_rate: 50  # 控制器更新頻率

    diff_drive_controller:
      type: diff_drive_controller/DiffDriveController

diff_drive_controller:
  ros__parameters:
    left_wheel_names: ["left_wheel_joint"]
    right_wheel_names: ["right_wheel_joint"]

    wheel_separation: 1.315  # **機器人左右輪的距離** 0.665 1.315
    wheel_radius: 0.09  # **輪子半徑**

    wheel_separation_multiplier: 1.0
    left_wheel_radius_multiplier: 1.0
    right_wheel_radius_multiplier: 1.0

    publish_rate: 50.0
    odom_frame_id: "odom"
    base_frame_id: "base_link"
    cmd_vel_topic: "/cmd_vel"
    use_stamped_vel: false

    open_loop: false  # **因為你有 encoder，應該設為 false**
    position_feedback: true
    enable_odom_tf: true

    cmd_vel_timeout: 0.5

    use_imu: true
    imu_topic: "/imu/data"  # **這要對應你的 IMU topic**
    estimate_yaw_angle: true

    # 速度限制 (根據你的機器人調整)
    linear.x.has_velocity_limits: true
    linear.x.max_velocity: 1.0
    linear.x.min_velocity: -1.0
    linear.x.has_acceleration_limits: true
    linear.x.max_acceleration: 2.0

    angular.z.has_velocity_limits: true
    angular.z.max_velocity: 1.5
    angular.z.min_velocity: -1.5
    angular.z.has_acceleration_limits: true
    angular.z.max_acceleration: 3.0

    covariance_diagonal: [0.05, 0.05, 0.0, 0.0, 0.0, 0.02]