controller_manager:
  ros__parameters:
    update_rate: 50

    motor_controller:
      type: diff_drive_controller/DiffDriveController

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

motor_controller:
  ros__parameters:
    publish_rate: 50.0
    base_frame_id: base_link
    odom_frame_id: odom

    left_wheel_names: [left_wheel_joint, left_front_joint]
    right_wheel_names: [right_front_joint, right_wheel_joint]

    wheel_separation: 0.65    # 左右輪距 Lx
    wheel_radius: 0.09

    use_stamped_vel: false
    open_loop: false

    enable_odom_tf: true

joint_state_broadcaster:
  ros__parameters:
    publish_rate: 50.0
